apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: flask-example
  name: jenkins-cicd
---
apiVersion: v1
kind: Service
metadata:
  name: flask-example
  namespace: jenkins-cicd
  labels:
    app: flask-example
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: flask-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-example
  namespace: jenkins-cicd
  labels:
    app: flask-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-example
  template:
    metadata:
      labels:
        app: flask-example
    spec:
      containers:
      - name: flask-example
        image: <REPO_NAME>/<APP_NAME>:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
